# Generated by Django 4.0.3 on 2022-04-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_url',
            new_name='url',
        ),
    ]
