# Generated by Django 4.0.3 on 2022-04-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_rename_photo_caption_photo_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
