# Generated by Django 4.0.3 on 2022-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
